mos arch support
DoumanAsh/ufmt-stdio pull request #1
Opened 2022-01-17 16:14 UTC by mrk-its

I just started using `ufmt` with `ufmt-stdio` on `mos-a800xl-none` (sic! - on 8-bit atari) and it works great, good job! Unfortunately libc there is very limited and I had to provide own backend using `putchar`. I was also thinking about exposing it under some feature, so it would be possible to use it on other targets without `libc` support.

2022-01-17 16:58 UTC, DoumanAsh commented
@mrk-its 

I'm not familiar with `mos`
What is it?
Do you know what C's standard library has there?
We could `extern` symbol that is missing in `libc` crate as putchar would be rather inefficient approach
But if there is no other choice it sounds good

2022-01-17 17:47 UTC, mrk-its commented
There is very fresh llvm fork adding experimental MOS-6502 support for llvm, wiki: https://llvm-mos.org/wiki/Welcome, github:  https://github.com/llvm-mos Based on that I added support for this architecture in my rust fork: https://github.com/mrk-its/rust/tree/mos_target - and I'm able to successfully target 8-bit atari this way.

libc is implemented in llvm-mos-sdk subproject: https://github.com/llvm-mos/llvm-mos-sdk but currently is still very limited. For example there are no files / file descriptors yet, no stdin / stdout / stderr. The only function implemented on all subtargets (c64, a800xl and sim) is putchar :) 

I agree that using putchar is ineffective, I will investigate better interface for that (maybe I can extend sdk and add support for write), but for now it works quite good.

And I'll understand you if you don't want to add support for such experimental and niche target :) and will keep using my fork (but cargo + crates.io works great, so it would be really nice to use your crate directly)

2022-01-17 23:39 UTC, DoumanAsh commented
@mrk-its Ok, from what I understand there is high chance that Atari never had something like `pinrtf` in which case I don't think it is so bad to your `putchar` but if you can confirm it that would be great.
What are chances that this target will become available in Rust?
I don't mind adding it as long as you can keep an eye on it and update when necessary.

2022-01-17 23:45 UTC, DoumanAsh requested changes

2022-01-17 23:45 UTC, DoumanAsh commented on src/imp/mos.rs
> +fn write(text: &str) {
Add `[inline(always)]`

2022-01-17 23:45 UTC, DoumanAsh commented on src/imp/mos.rs
> +    fn putchar(c: u8);
Please add reference to https://github.com/llvm-mos/llvm-mos-sdk

2022-01-18 00:21 UTC, mrk-its commented
> @mrk-its Ok, from what I understand there is high chance that Atari never had something like `pinrtf` in which case I don't think it is so bad to use `putchar` but if you can confirm it that would be great.

`printf` is available (but still internally implemented with putchar), isn't variable number of args some problem here in terms of FFI? No idea how to create `extern "C"` declaration for it.

> What are chances that this target will become available in Rust?

It depends on if llvm-mos get merged upstream. But llvm part is taken very seriously and  has very high quality so chances are quite big IMHO.

> I don't mind adding it as long as you can keep an eye on it and update when necessary.

Great, of course I'm going to keep an eye on it.

2022-01-18 01:19 UTC, DoumanAsh commented
> printf is implemented in llvm-mos-sdk, but also with putchar. Isn't variable number of args some problem here in terms of FFI?

It is not all that difficult
```rust
    extern "C" {
        pub fn printf(format: *const i8, ...) -> int;
    }
```

But if it is done via `puchar` then there is not much difference from using `putchar` directly

2022-01-18 01:19 UTC, DoumanAsh approved these changes

2022-01-18 01:24 UTC, merged

2022-01-18 01:25 UTC, DoumanAsh commented
@mrk-its I've released 0.2.0 with your patch